=== es3649/card-games/schemas/game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
        "shared_zones",
        "player_zones",
        "players",
        "decks"
    ],
    "properties": {
        "tricks": {
            "type": "boolean",
            "description": "whether the game is played in tricks"
        },
        "turns": {
            "type": "boolean",
            "description": "whether the game is player in turns"
        },
        "shared_zones": {
            "type": "array",
            "description": "an enumeration of any global card zones: each of these zones is created only the specified number of times, and are not duplicated depending on the player count",
            "items": {
                "$ref": "./zone_descriptor.schema.json"
            }
        },
        "player_zones": {
            "type": "array",
            "description": "an enumaration of player-specific zones: a copy of each of these zones is create for each player in the game",
            "items": {
                "$ref": "./zone_descriptor.schema.json"
            }
        },
        "decks": {
            "type": "array",
            "description": "an enumeration and labelling of the decks which will be used in the game",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "source"
                ],
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "the name which is used within this object to refer to this deck"
                    },
                    "source": {
                        "type": "string",
                        "description": "path to a source deck file"
                    },
                    "each_player": {
                        "type": "boolean",
                        "description": "whether a copy of this deck should be created for each player in the game"
                    },
                    "aces_high": {
                        "type": "boolean",
                        "description": "in games where card values can be assigned and well ordered, should aces/ones be considered high or low"
                    }
                }
            }
        },
        "players": {
            "allOf": [{ "$ref": "./count.schema.json" }],
            "description": "the number of players that the game accomodates"
        }
    }
}

=== es3649/card-games/games/nerts.json
{
    "$schema": "../schemas/game.schema.json",
    "decks": [{
        "name": "pack",
        "source": "../decks/standard-52.json",
        "each_player": true
    }],
    "players": [2,4],
    "player_zones": [{
        "name": "nerts",
        "zone_visibility": "all",
        "card_visibility": 1,
        "control": "owner",
        "decks": ["pack"],
        "size": {
            "initial": 13
        },
        "order": "fixed-fifo"
    },{
        "name": "work",
        "zone_visibility": "all",
        "card_visibility": "all",
        "control": "owner",
        "decks": ["pack"],
        "size": {
            "initial": 1
        },
        "order": "fixed-lifo",
        "count": [0, 4]
    },{
        "name": "stock",
        "card_visibility": "none",
        "control": "owner",
        "decks": ["pack"],
        "is_library": true,
        "order": "fixed-fifo",
        "replenish": {
            "from": ["waste"],
            "shuffle": false,
            "on_empty": true
        }
    },{
        "name": "waste",
        "card_visibility": 1,
        "zone_visibility": "owner",
        "control": "owner",
        "decks": ["pack"],
        "order": "fixed-lifo"
    }],
    "shared_zones": [{
        "name": "play",
        "card_visibility": 1,
        "zone_visibility": "all",
        "control": "all",
        "decks": ["pack"],
        "size": {
            "limits": [0, 13]
        },
        "order": "fixed-lifo",
        "count": [0, 16] 
    }]
}

=== es3649/card-games/games/uno.json
{
    "$schema": "../schemas/game.schema.json",
    "shared_zones": [{
        "name": "draw_pile",
        "decks": ["the_deck"],
        "control": "active-player",
        "is_library": true,
        "order": "fixed-fifo",
        "replenish": {
            "from": ["discard_pile"],
            "shuffle": true,
            "on_empty": true
        }
    },{
        "name": "discard_pile",
        "decks": ["the_deck"],
        "control": "all",
        "zone_visibility": "all",
        "order": "fixed-lifo",
        "size": {
            "initial": 1
        }
    }],
    "player_zones": [{
        "name": "hand",
        "decks": ["the_deck"],
        "card_visibility": "all",
        "zone_visibility": "owner",
        "control": "owner",
        "size": {
            "initial": 7
        },
        "order": "any"
    }],
    "players": [2,8],
    "decks": [{
        "name": "the_deck",
        "source": "../decks/uno.json"
    }]
}

=== es3649/card-games/games/canasta.json
{
    "$schema": "../schemas/game.schema.json",
    "decks": [{
        "name": "canasta",
        "source": "../decks/canasta.json"
    }],
    "players": [2,3],
    "turns": true,
    "shared_zones": [{
        "name": "deck",
        "decks": ["canasta"],
        "is_library": true,
        "control": "all",
        "order": "shuffled"
    },{
        "name": "discard_pile",
        "decks": ["canasta"],
        "card_visibility": 1,
        "zone_visibility": "all",
        "control": "active-player",
        "order": "fixed-lifo",
        "designations": {
            "values": ["frozen"]
        }
    }],
    "player_zones": [{
        "name": "hand",
        "card_visibility": "all",
        "zone_visibility": "owner",
        "control": "owner",
        "decks": ["canasta"],
        "order": "any"
    },{
        "name": "play",
        "card_visibility": "all",
        "zone_visibility": "all",
        "control": "owner",
        "decks": ["canasta"],
        "order": "any",
        "count": "*"
    },{
        "name": "bonuses",
        "card_visibility": "all",
        "zone_visibility": "all",
        "control": "owner",
        "order": "any",
        "decks": ["canasta"]
    }]
}
